### PR TITLE
Add games styles

### PR DESCRIPTION
**Pull request by karynatrychyk**
Great collection and thanks for sharing it! Perhaps it could complement to it.
Hope it did it right with pull request)

The prompt was "sphere, <style> --seed 4776"

### CODE REVIEW

**Comment by willwulfken** [comment]
I happened to notice this fork luckily. The pull request didn't actually go through. Try doing it through [this page](https://github.com/willwulfken/MidJourney-Styles-and-Keywords-Reference/pulls)

**Comment by karynatrychyk** [comment]
All right, I just didn't merge it. Thought it needed some kind of verification before I could do it)

**Comment by willwulfken** [comment]
Basically, on the page I sent you, click "create pull request". You're going to want to select mine on the left and yours on the right (there is an arrow between the selection boxes showing which one is going into the other one)

Once you do that, I can then go ahead and accept the request

**Comment by karynatrychyk** [comment]
Okay, hope it works now.
Sorry, I'm an artist and don't normally work with git and pull requests)

**Comment by willwulfken** [comment]
It popped up! It's not a problem. I don't mind helping people out with it.
Thank you for your submission. I'll do my best to merge it by the end of the day.

**Comment by willwulfken** [comment]
Just one quick question. I noticed the images are labeled "sphere_<style>_style". Did you use a prompt like "sphere, Fallout style" or "sphere, Fallout"?

Just want to make sure I label them correctly

**Comment by karynatrychyk** [comment]
I used "sphere, Fallout style".

**Comment by willwulfken** [comment]
I just finished the commit.

Here are the styles you submitted (In [🖥 Digital] > [🖥🕹 Video Game Styles])
[MJV3 > 🖼 Themes and Design Styles](https://github.com/willwulfken/MidJourney-Styles-and-Keywords-Reference/blob/main/Pages/MJ_V3/Style_Pages/Themes_and_Design_Styles.md)

I also went ahead and generated them for the "Just The Style" Page (In [🖥 Digital] > [🖥🕹 Video Game Styles])
[MJV3 > Just The Style > 🖼 Themes and Design Styles](https://github.com/willwulfken/MidJourney-Styles-and-Keywords-Reference/blob/main/Pages/MJ_V3/Style_Pages/Just_The_Style/Themes_and_Design_Styles.md)

**Comment by karynatrychyk** [comment]
Thank you! It's a great job you're doing.

**Comment by willwulfken** [comment]
Thank you! Also, thank you for the amazing list and images of video game styles!

**Pull request merged**
